name: coffee_mobile_app_modul2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4

dev_dependencies: 
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/svgs/
    - assets/images/
  uses-material-design: true

